### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by magnetic-pi** [danirus/django-wysihtml5#12]
Would it be possible to set the default layout of the wysiwyg editor buttons to be bootstrap buttons? Or at least include "btn" in the class for each button?

I set the model field as the directions state:

```
comment = Wysihtml5TextField(verbose_name='', blank=False)
```

Then in my model I usually set the widget attributes:

```
def __init__(self, *args, **kwargs):                                                                                                    
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['comment'].widget.attrs={'class':'textbody', 'placeholder':"Please leave your comment here.", 'rows': 20, 'cols': 80}
```

The problem is that I get the old layout and not the twitter bootstrap layout. I've been doing research and found your comment here:

http://stackoverflow.com/questions/16165825/how-to-use-django-wysihtml5-in-frontend-forms/16394094#16394094

I tried importing:

```
from topic.twitter_bootstrap import Wysihtml5BootstrapWidget

self.fields['comment'].Wysihtml5BootstrapWidget.attrs={'class':'textbody', 'placeholder':"Please leave your comment here.", 'rows': 20, 'cols': 80}
```

However, this did (as I was expecting, but not 100% sure) not work.

Can you think of any other/easier way to get the twitter bootstrap layout by default? I really feel with that layout as the default, this module would become very popular, very quickly.

Also, have you seen: http://mindmup.github.io/bootstrap-wysiwyg/

Check it out in Chrome, as it offers voice input which is incredible.

**Comment by danirus** [comment]
Twitter-bootstrap is just a frontend-template, a very popular one, but there are others. Django-wysihtml5 is just a super simple app to bring Wysihtml5 to Django. It has to be frontend-template agnostic, so that you can use Twitter-bootstrap, HTML5 Boilerplate, Jquery UI, or your own. The default toolbar that shows up in the admin UI is just a simple one I did to provide a simple frontend-template agnostic toolbar, I'm not a Web Designer (that's quite obvious given such an ugly buttons). You can replace them with your own choice.

I decided to use bootstrap-wysihtml5 in the demo as an example to demonstrate how you can plug your frontend-template of choice. Either a third party one like twitter-bootstrap, HTML5 Boilerplate, or your own.

To create a Twitter-bootstrap Wysihtml5 textarea widget for your comment field, first create a form and then tell that the comment field in the form must be rendered using the Wyishtml5BootstrapWidget:

```
from twitter_bootstrap import Wyishtml5BootstrapWidget

class MyForm(forms.Form):
    [...other fields...]
    comment = fields.CharField(widget=Wyishtml5BootstrapWidget)
```

**Comment by magnetic-pi** [comment]
Sorry I was on vacation so I am just getting back to this. Sounds fair enough. I am closing this issue.
